{
  "artifacts": [],
  "command": "my_main",
  "experiment": {
    "base_dir": "d:\\code\\pymarl",
    "dependencies": [
      "numpy==1.23.1",
      "PyYAML==6.0.2",
      "sacred==0.8.7",
      "torch==1.13.1+cu117"
    ],
    "mainfile": "main.py",
    "name": "pymarl",
    "repositories": [],
    "sources": [
      [
        "main.py",
        "_sources\\main_7e91dbcc6085c7cbc022cfd7cceee614.py"
      ],
      [
        "run.py",
        "_sources\\run_3d13dbdeea410bcf5bb87beb4266819c.py"
      ],
      [
        "utils\\logging.py",
        "_sources\\logging_1c1c5c83be7ac7b7b69888b3bcb127e3.py"
      ]
    ]
  },
  "fail_trace": [
    "Traceback (most recent call last):\n",
    "  File \"C:\\Users\\maxli\\anaconda3\\envs\\pymarl\\lib\\site-packages\\sacred\\config\\captured_function.py\", line 42, in captured_function\n    result = wrapped(*args, **kwargs)\n",
    "  File \"d:\\code\\pymarl\\main.py\", line 37, in my_main\n    run(_run, config, _log)\n",
    "  File \"d:\\code\\pymarl\\run.py\", line 51, in run\n    run_sequential(args=args, logger=logger)\n",
    "  File \"d:\\code\\pymarl\\run.py\", line 210, in run_sequential\n    episode_batch = runner.run(test_mode=False)\n",
    "  File \"d:\\code\\pymarl\\runners\\episode_runner.py\", line 53, in run\n    self.reset()\n",
    "  File \"d:\\code\\pymarl\\runners\\episode_runner.py\", line 49, in reset\n    self.env.reset()\n",
    "  File \"C:\\Users\\maxli\\anaconda3\\envs\\pymarl\\lib\\site-packages\\smac\\env\\starcraft2\\starcraft2.py\", line 350, in reset\n    self._launch()\n",
    "  File \"C:\\Users\\maxli\\anaconda3\\envs\\pymarl\\lib\\site-packages\\smac\\env\\starcraft2\\starcraft2.py\", line 307, in _launch\n    map_data=self._run_config.map_data(_map.path)),\n",
    "  File \"C:\\Users\\maxli\\anaconda3\\envs\\pymarl\\lib\\site-packages\\pysc2\\run_configs\\lib.py\", line 142, in map_data\n    raise ValueError(f\"Map {map_name} not found in {self.data_dir}/Maps.\")\n",
    "ValueError: Map SMAC_Maps\\3m.SC2Map not found in D:\\StarCraft II/Maps.\n"
  ],
  "heartbeat": "2024-12-06T12:07:10.319195",
  "host": {
    "ENV": {},
    "cpu": "Intel(R) Core(TM) i7-10750H CPU @ 2.60GHz",
    "gpus": {
      "driver_version": "560.70",
      "gpus": [
        {
          "model": "NVIDIA GeForce GTX 1650",
          "persistence_mode": false,
          "total_memory": 4096
        }
      ]
    },
    "hostname": "NOI-LAPTOP",
    "os": [
      "Windows",
      "Windows-10-10.0.19045-SP0"
    ],
    "python_version": "3.10.14"
  },
  "meta": {
    "command": "my_main",
    "config_updates": {
      "save_model": true,
      "save_model_interval": 1000,
      "t_max": 50000,
      "use_tensorboard": true
    },
    "named_configs": [],
    "options": {
      "--beat-interval": null,
      "--capture": null,
      "--comment": null,
      "--debug": false,
      "--enforce_clean": false,
      "--file_storage": null,
      "--force": false,
      "--help": false,
      "--id": null,
      "--loglevel": null,
      "--mongo_db": null,
      "--name": null,
      "--pdb": false,
      "--print-config": false,
      "--priority": null,
      "--queue": false,
      "--s3": null,
      "--sql": null,
      "--tiny_db": null,
      "--unobserved": false,
      "COMMAND": null,
      "UPDATE": [
        "save_model=True",
        "use_tensorboard=True",
        "save_model_interval=1000",
        "t_max=50000"
      ],
      "help": false,
      "with": true
    }
  },
  "resources": [],
  "result": null,
  "start_time": "2024-12-06T12:06:57.292435",
  "status": "FAILED",
  "stop_time": "2024-12-06T12:07:10.323197"
}